### ISSUE TITLE
Move to mamba

### ISSUE THREAD

**Issue by martinclaus** [martinclaus/py-da-stack#19]
[Mamba](https://github.com/mamba-org/mamba) is a fully(?) compatible [conda](https://github.com/conda/conda) replacement, written in C++. It promises to be more performant in solving dependencies and to support multi-threaded downloading.

There is also [micromamba](https://mamba.readthedocs.io/en/latest/micromamba.html), the equivalent to miniconda but being C++ only, it comes without preinstalled Python. However, it is presently still marked as experimental.

**Comment by martinclaus** [comment]
Ping @willirath and @kathoef

**Comment by willirath** [comment]
If I recall correctly, @kathoef is actively using mamba in some of her environments already. I'm using it in managing test envs for, e.g., Xoak. Also, Binder and Pangeo are using Mamba already.

So I'd go for it.

**Comment by martinclaus** [comment]
> If I recall correctly, @kathoef is actively using mamba in some of her environments already. I'm using it in managing test envs for, e.g., Xoak. Also, Binder and Pangeo are using Mamba already.
> 
> So I'd go for it.

Are they also using micromamba?

**Comment by willirath** [comment]
Binder / Repo2Docker uses only mamba: <https://github.com/jupyterhub/repo2docker/blob/b609424f5dacf0a08c3302072b21aed4a9dcbf94/repo2docker/buildpacks/conda/install-miniforge.bash>

They've not (yet ?) moved to micromamba, however: https://github.com/jupyterhub/repo2docker/pull/919#issuecomment-661020577

**Comment by kathoef** [comment]
Yes, I am using something like this

```
RUN wget https://repo.anaconda.com/miniconda/${MINICONDA_VERSION} --quiet --directory-prefix ${HOME} \
 && bash ${HOME}/${MINICONDA_VERSION} -f -b -p ${TARGET_DIR} \
 && rm -rf ${HOME}/${MINICONDA_VERSION} \
 && ${TARGET_DIR}/bin/conda install -n base -c conda-forge mamba \
 && source ${TARGET_DIR}/etc/profile.d/conda.sh && conda activate base \
 && mamba install -n base -c conda-forge ...
```

and it works very well. I do not have any experience with micromamba. The documentation says,

> Note that micromamba is still in early development and not considered ready-for-general-usage yet! It has been used with great success in CI systems, though, and we encourage this usage.

Thinking about it, I would argue that using Jupyter from a container environment is very close to classic CI workflows, so it's probably safe to use micromamba as we are not administrating a very complex set of several conda environments?

Also, Singularity containers are mostly read-only and even Docker-only workflows would be targeted rather at changing a container's default environment package list (and rebuilding from scratch), than occasionally and interactively adding packages (i.e. the classic interactive conda usage, which might be the thing that is not yet fully supported, see @willirath's comment).

**Comment by martinclaus** [comment]
OK, so let's move to Mambaforge as a first step and maybe later switch to micromamba to have no Python in the base environment.

**Comment by martinclaus** [comment]
From my experience, mamba is not a drop-in replacement for conda. Some crucial things are still missing today, such as full environment management options. Better to postpone the move to micromamba for now.
