### ISSUE TITLE
Prevent scope file permission problems for Linux host systems

### ISSUE THREAD

**Issue by kathoef** [martinclaus/py-da-stack#7]
This can be done with on-board features provided by the Jupyter docker-stacks, where [details are found here](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/common.html#docker-options).

Basically, instead of,

```
docker run -p 8888:8888 -v $(pwd):/home/jovyan/work --rm jupyter/base-notebook:latest
```

Run the Docker container with,

```
docker run -p 8888:8888 -v $(pwd):/home/jovyan/work -e NB_UID=$(id -u) -e NB_GID=$(id -g) --user root --rm jupyter/base-notebook:latest
```

From the docs,

> -e NB_UID=1000 - Instructs the startup script to switch the numeric user ID of $NB_USER to the given value. This feature is useful when mounting host volumes with specific owner permissions. For this option to take effect, you must run the container with --user root. (The startup script will su $NB_USER after adjusting the user ID.) You might consider using modern Docker options --user and --group-add instead. See the last bullet below for details.

> -e NB_GID=100 - Instructs the startup script to change the primary group of$NB_USER to $NB_GID (the new group is added with a name of $NB_GROUP if it is defined, otherwise the group is named $NB_USER). This feature is useful when mounting host volumes with specific group permissions. For this option to take effect, you must run the container with --user root. (The startup script will su $NB_USER after adjusting the group ID.) You might consider using modern Docker options --user and --group-add instead. See the last bullet below for details. The user is added to supplemental group users (gid 100) in order to allow write access to the home directory and /opt/conda. If you override the user/group logic, ensure the user stays in group users if you want them to be able to modify files in the image.

The mentioned last bullet says,

> --user 5000 --group-add users - Launches the container with a specific user ID and adds that user to the users group so that it can modify files in the default home directory and /opt/conda. You can use these arguments as alternatives to setting $NB_UID and $NB_GID.

Doing the following works as well,

```
docker run -p 8888:8888 -v $(pwd):/home/jovyan/work --user $(id -u):$(id -g) --group-add users --rm jupyter/base-notebook:latest
```

but as no entries in `/etc/passwd` and `/etc/group` are setup in the container, shell sessions start with warnings such as "groups: cannot find name for group ID 1000". Therefore, it might be best to stick with the first approach?

**Comment by martinclaus** [comment]
Looks like updating the Readme is sufficient.
